spring:
  writerdatasource:
    jdbcUrl: jdbc:mysql://localhost:3306/employeedirectory
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  readerdatasource:
    jdbcUrl: jdbc:mysql://localhost:3306/employeedirectory
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      mode: always

logging: 
  level:
    root: ERROR
    com.example : debug


